version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: tusolucionautomatica
    ports:
      - "8080:80"
    volumes:
      - ./tusolucionautomatica.conf:/etc/nginx/tusolucionautomatica.conf:ro
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped 