name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to EC2 via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}     
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          source: "./frontend/*"
          target: "/usr/share/nginx/html/"
          strip_components: 1 